export default {
  ACCOUNT: '/account',
  ADD_GARDEN: '/garden/add',
  ABOUT_SUPERFAN: '/about-superfan',
  ABOUT_US: '/about-us',
  AUTH_ACTION: '/auth/action',
  BECOME_SUPERFAN: '/become-superfan',
  CHAT: '/chat',
  COOKIE_POLICY: '/terms/cookies',
  FAQ: '/info/faq',
  HOME: '/',
  MANAGE_GARDEN: '/garden/manage',
  MAP: '/explore',
  PRIVACY_POLICY: '/terms/privacy-policy',
  REGISTER: '/register',
  REQUEST_PASSWORD_RESET: '/request-password-reset',
  RESET_PASSWORD: '/reset-password',
  RULES: '/info/rules',
  SIGN_IN: '/sign-in',
  SUPERFAN_PAYMENT: '/become-superfan/payment',
  TERMS_OF_USE: '/terms/terms-of-use',
  SUPERFAN_THANK_YOU: '/become-superfan/thank-you'
};
